### ISSUE TITLE
train.py run errors

### ISSUE THREAD

**Issue by KKKlose** [zhangjunh/DR-GAN-by-pytorch#9]
When I run train.py use Single-Image DR-GAN or Multi-Image DR-GAN on win10 , both warning:
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

What's the problem? Thank you!

**Comment by zhangjunh** [comment]
@KKKlose https://stackoverflow.com/questions/29690091/python2-7-exception-the-freeze-support-line-can-be-omitted-if-the-program

**Comment by zhangjunh** [comment]
@KKKlose Set the batchsize = 1 and watch the usage of GPU.

**Comment by KKKlose** [comment]
The usage of GPU is only 9%

**Comment by KKKlose** [comment]
OK ,thank you for your reply.

**Comment by haha1958** [comment]
when i run train.py ,i get an errror ? I try to solve it but i donnot know how it come,can you help me?Thank you  

Traceback (most recent call last):
  File "train.py", line 32, in <module>
    model.module.forward(data)
  File "model/DRGAN.py", line 120, in forward
    self.syn_image = self.G(self.image, self.input_pose, self.noise)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "model/Component.py", line 264, in forward
    x = self.enc(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "model/Component.py", line 191, in forward
    x = self.conv_layers(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "model/Component.py", line 83, in forward
    x = self.layers(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)

**Comment by zhangjunh** [comment]
Hi @haha1958 , I searched your error massages and it is likely caused by using multi-gpu. I was only using this code running in single gpu. If you have to run them in multi-gpu, you must change some code and debug by yourself. Hope that will be helpful to you.

**Comment by haha1958** [comment]
thanks for your reply ,I get it
